# Generated by Django 3.2.12 on 2023-12-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(default='', max_length=20, verbose_name='性别')),
                ('nation', models.CharField(default='', max_length=20, verbose_name='民族')),
                ('birthday', models.DateField(default='', max_length=20, verbose_name='出生日期')),
                ('politic', models.CharField(default='', max_length=20, verbose_name='政治面貌')),
                ('Sno', models.CharField(default='', max_length=100, verbose_name='学号')),
                ('domicile', models.CharField(default='', max_length=200, verbose_name='户籍地')),
                ('ID_card', models.CharField(default='', max_length=200, verbose_name='身份证号')),
                ('enlist_time', models.DateField(default='', max_length=20, verbose_name='入伍时间')),
                ('retire_time', models.DateField(default='', max_length=20, verbose_name='退役时间')),
                ('before_teacher', models.CharField(default='', max_length=20, verbose_name='入伍前班导师')),
                ('retire_teacher', models.CharField(default='', max_length=20, verbose_name='退伍后班导师')),
                ('before_class', models.CharField(default='', max_length=20, verbose_name='入伍前学院班级')),
                ('retire_class', models.CharField(default='', max_length=20, verbose_name='退伍后学院班级')),
                ('searvice_troops', models.CharField(default='', max_length=20, verbose_name='服役部队')),
                ('duties', models.CharField(default='', max_length=20, verbose_name='职务')),
                ('number', models.CharField(default='', max_length=20, verbose_name='本人电话')),
                ('family_number', models.CharField(default='', max_length=20, verbose_name='家庭电话')),
                ('enlist_place', models.CharField(default='', max_length=20, verbose_name='入伍地')),
                ('pend', models.FileField(default='', max_length=20, null=True, upload_to='', verbose_name='挂科科目')),
                ('rewards', models.FileField(default='', max_length=20, null=True, upload_to='', verbose_name='奖惩情况')),
                ('certifiate', models.FileField(default='', max_length=20, null=True, upload_to='', verbose_name='专业培训及证书')),
                ('personal_photo', models.CharField(max_length=200, verbose_name='个人照')),
                ('enlist_photo', models.CharField(max_length=200, verbose_name='入伍通知书')),
                ('retire_photo', models.CharField(max_length=200, verbose_name='退役证')),
                ('sign_photo', models.CharField(max_length=200, verbose_name='本人签字')),
                ('isValid', models.BooleanField(default=1, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '基本信息表',
                'verbose_name_plural': '基本信息表',
            },
        ),
    ]
