# Generated by Django 2.0 on 2023-12-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20231214_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='certifiate',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='专业培训及证书'),
        ),
    ]
