# Generated by Django 2.0 on 2024-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminlogin', '0003_auto_20240312_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
